services:
  browserless:
    image: ghcr.io/browserless/chromium:v2.44.0
    environment:
      - CONNECTION_TIMEOUT=60000
      - KEEP_ALIVE=true
    ports:
      - "3000:3000"

  postgres:
    image: postgres:16.9
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - "${POSTGRES_PORT}:5432"
    depends_on:
      - browserless
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 3s
      retries: 3

  maildev:
    image: maildev/maildev
    environment:
      - TZ=Asia/Yekaterinburg
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
    ports:
      - "8080:1080"
      - "1025:1025"
    depends_on:
      - postgres
    logging:
      driver: "json-file"
      options:
        max-size: "1m"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - backend_db:/app/data          # уже существующий том для данных приложения
      - model_cache:/app/cache      # новый том для кэша моделей
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - maildev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data:
  backend_db:
  model_cache:    # объявляем новый том